database = [{'name': 'T-Series',
             'Follower_count': 245,
             'Content': 'Official channel of the Indian record label and movie studio T-Series',
             'Country': 'India'},
            {'name': 'MrBeast',
             'Follower_count': 166,
             'Content': "American YouTuber Jimmy Donaldson's channel featuring stunts, tricks, and giveaways",
             'Country': 'USA'},
            {'name': 'Cocomelon',
             'Follower_count': 162,
             'Content': 'Animated nursery rhymes by US-based company Treasure Studio',
             'Country': 'USA'},
            {'name': 'Sony Entertainment Television India',
             'Follower_count': 158,
             'Content': 'Sony Entertainment Television in Hindi',
             'Country': 'India'},
            {'name': 'Kids Diana Show',
             'Follower_count': 112,
             'Content': 'Kid-oriented vlogs, reviews, and role-playing content by 8-year-old Ukrainian-American '
                        'YouTuber Eva Diana Kiddish',
             'Country': 'USA'},
            {'name': 'PewDiePie',
             'Follower_count': 111,
             'Content': "Swedish YouTuber Felix Kjellberg's comedy and gaming channel",
             'Country': 'Sweden'},
            {'name': 'Like Nastya',
             'Follower_count': 106,
             'Content': 'Stories and role-play for kids by 9-year-old Russian-American YouTuber Anastasia Radzinskaya',
             'Country': 'Russia'},
            {'name': 'Vlad and Niki',
             'Follower_count': 98.8,
             'Content': 'Child-oriented vlogs and role-play by 9- and 7-year-old YouTubers Vladislav and Nikita '
                        'Vashketov',
             'Country': 'Russia'},
            {'name': 'Zee Music Company',
             'Follower_count': 96.6,
             'Content': 'Official channel of Indian music company Zee Music Company (ZMC)',
             'Country': 'India'},
            {'name': 'WWE',
             'Follower_count': 96,
             'Content': 'Official channel of World Wrestling Entertainment, Inc.',
             'Country': 'USA'},
            {'name': 'Blackpink',
             'Follower_count': 89.8,
             'Content': 'Official channel of the South Korean girl group Blackpink',
             'Country': 'South Korea'},
            {'name': 'Goldmines',
             'Follower_count': 86.9,
             'Content': 'Official channel of Indian movie company Goldmines Telefilms',
             'Country': 'India'},
            {'name': 'Sony SAB',
             'Follower_count': 82.7,
             'Content': 'Official channel of the Indian TV channel Sony SAB',
             'Country': 'India'},
            {'name': '5-Minute Crafts',
             'Follower_count': 80.1,
             'Content': 'DIY channel by TheSoul Publishing',
             'Country': 'USA'},
            {'name': 'BangtanTV',
             'Follower_count': 75.6,
             'Content': 'Official channel of the South Korean boy band BTS',
             'Country': 'South Korea'},
            {'name': 'Justin Bieber',
             'Follower_count': 71.6,
             'Content': 'Official channel of Canadian singer Justin Bieber',
             'Country': 'USA'},
            {'name': 'Hybe Labels',
             'Follower_count': 71.1,
             'Content': 'Official channel of the South Korean record label HYBE',
             'Country': 'South Korea'},
            {'name': 'Zee TV',
             'Follower_count': 70.3,
             'Content': 'Official channel of the Indian TV channel ZEE TV',
             'Country': 'India'},
            {'name': 'Pinkfong',
             'Follower_count': 68.1,
             'Content': "Official channel of the South Korean children's songs company (most famous for 'Baby Shark')",
             'Country': 'South Korea'},
            {'name': 'Canal KondZilla',
             'Follower_count': 66.5,
             'Content': 'Official channel of the Brazilian music video production company KondZilla',
             'Country': 'Brazil'},
            {'name': 'ChuChu TV Nursery Rhymes & Kids Songs',
             'Follower_count': 65.9,
             'Content': 'Indian network of edutainment YouTube channels for kids',
             'Country': 'India'},
            {'name': 'Shemaroo Entertainment',
             'Follower_count': 65.5,
             'Content': 'Official channel of the Indian multi-media entertainment company Shemaroo Entertainment',
             'Country': 'India'},
            {'name': 'Colors TV',
             'Follower_count': 64.4,
             'Content': 'Official channel of Indian broadcast network Colors TV',
             'Country': 'India'},
            {'name': 'T-Series Bhakti Sagar',
             'Follower_count': 60.8,
             'Content': 'Devotional movies division of T-Series',
             'Country': 'India'},
            {'name': 'Dude Perfect',
             'Follower_count': 59.5,
             'Content': 'Dude Perfect was launched by five American YouTubers back in 2009 and features trick shots, '
                        'stunts, and battles',
             'Country': 'USA'},
            {'name': 'Movieclips',
             'Follower_count': 59.5,
             'Content': 'Official channel of Fandango Movieclips which features short sequences from popular movies',
             'Country': 'USA'},
            {'name': 'Tips Official',
             'Follower_count': 59.3,
             'Content': 'Official channel of Indian record label Tips Industries Limited',
             'Country': 'India'},
            {'name': 'El Reino Infantil',
             'Follower_count': 58.3,
             'Content': 'Argentine channel by Leader Music featuring songs for kids',
             'Country': 'USA'},
            {'name': 'Wave Music',
             'Follower_count': 58,
             'Content': 'Official channel of Indian music company Wave Music',
             'Country': 'India'},
            {'name': 'Aaj Tak',
             'Follower_count': 57.5,
             'Content': 'Official channel of Indian news channel Aaj Tak',
             'Country': 'India'},
            {'name': 'Sony Music India',
             'Follower_count': 57.1,
             'Content': 'Hindi-language channel of Sony Music',
             'Country': 'India'},
            {'name': 'Eminem',
             'Follower_count': 56.8,
             'Content': 'Official channel of American rapper and record producer Eminem',
             'Country': 'USA'},
            {'name': 'Marshmello',
             'Follower_count': 56.4,
             'Content': 'Official channel of American DJ and producer Marshmello (Christopher Comstock)',
             'Country': 'USA'},
            {'name': 'Yash Raj Films',
             'Follower_count': 54.5,
             'Content': 'Official channel of Indian movie production company Yash Raj Films',
             'Country': 'India'},
            {'name': 'LooLoo Kids',
             'Follower_count': 54,
             'Content': "US-based edutainment children's channel",
             'Country': 'USA'},
            {'name': 'Ed Sheeran',
             'Follower_count': 53.5,
             'Content': 'Official channel of English singer Ed Sheeran',
             'Country': 'USA'},
            {'name': 'Infobells',
             'Follower_count': 53.3,
             'Content': 'Official channel of Hindi animation and nursery rhyme company Infobells',
             'Country': 'India'},
            {'name': 'Ariana Grande',
             'Follower_count': 52.7,
             'Content': 'Official channel of American singer Ariana Grande',
             'Country': 'USA'},
            {'name': 'Taylor Swift',
             'Follower_count': 52.9,
             'Content': 'Official channel of American singer Taylor Swift',
             'Country': 'USA'},
            {'name': 'BillionSurpriseToys',
             'Follower_count': 52.2,
             'Content': 'Official channel of UAE animation and nursery rhyme clip company Animacast',
             'Country': 'UAE'},
            {'name': 'JuegaGerman',
             'Follower_count': 48.1,
             'Content': 'Gameplay channel of Chilean YouTuber GermÃ¡n Alejandro Garmendia Aranis',
             'Country': 'USA'},
            {'name': 'Billie Eilish',
             'Follower_count': 47.9,
             'Content': 'Official channel of American singer Billie Eilish',
             'Country': 'USA'},
            {'name': 'Shemaroo',
             'Follower_count': 47.3,
             'Content': 'Official channel of Hindi movie and entertainment company Shemaroo Entertainment',
             'Country': 'India'},
            {'name': 'Get Movies',
             'Follower_count': 47.4,
             'Content': 'Russian-language channel with animated kids and family content',
             'Country': 'Russia'},
            {'name': 'Badabun',
             'Follower_count': 46.8,
             'Content': 'Official channel of Mexican multimedia company Badabun',
             'Country': 'Brazil'},
            {'name': 'SonyMusicIndiaVEVO',
             'Follower_count': 46.6,
             'Content': 'Hindi-language music channel of Sony Music',
             'Country': 'India'},
            {'name': 'A4',
             'Follower_count': 46.3,
             'Content': 'Comedy and sketches by the Russian-language A4 group - Vlad, Rivi, Glent and Seryoga',
             'Country': 'Russia'},
            {'name': 'Fernanfloo',
             'Follower_count': 46.1,
             'Content': 'Comedy and gaming channel of Salvadoran YouTuber Luis Fernando Flores',
             'Country': 'USA'},
            {'name': 'Bad Bunny',
             'Follower_count': 46.1,
             'Content': 'Official channel of Puerto Rican Rapper Bad Bunny',
             'Country': 'USA'},
            {'name': 'Voot Kids',
             'Follower_count': 45.5,
             'Content': 'Official channel of kids content subscription service Voot Kids',
             'Country': 'India'}]

logo = """
  ___ ___  .__ .__                                                .___            .____                                                 ________                           
 /   |   \ |__||  |__    ____ _______         _____     ____    __| _/            |    |     ____ __  _  __  ____ _______              /  _____/ _____     _____    ____   
/    ~    \|  ||  |  \ _/ __ \\_  __ \        \__  \   /    \  / __ |             |    |    /  _ \\ \/ \/ /_/ __ \\_  __ \            /   \  ___ \__  \   /     \ _/ __ \  
\    Y    /|  ||   Y  \\  ___/ |  | \/         / __ \_|   |  \/ /_/ |             |    |___(  <_> )\     / \  ___/ |  | \/            \    \_\  \ / __ \_|  Y Y  \\  ___/  
 \___|_  / |__||___|  / \___  >|__|           (____  /|___|  /\____ |             |_______ \\____/  \/\_/   \___  >|__|                \______  /(____  /|__|_|  / \___  > 
       \/           \/      \/                     \/      \/      \/                     \/                    \/                            \/      \/       \/      \/  
                                                                                                                                                                                                                                                                                                      
"""

vs= """

____   ____       
\   \ /   /______ 
 \   Y   //  ___/ 
  \     / \___ \  
   \___/ /____  > 
              \/  
                  


"""